### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ocioran** [dhcgn/BeyondCompareSQLitePlugin#15]
Hi,

Could this tool have Linux support? Personally, I use Ubuntu.

Thanks,
Olga

**Comment by dhcgn** [comment]
I will port this lib to .net core 3 when it is released. Then a can release
a single executable for Ubuntu.

Olga Cioran <notifications@github.com> schrieb am Fr., 8. März 2019, 12:33:

**Comment by PieterSmith-TomTom** [comment]
Hi @dhcgn ,
How is this going? .net core 3 has been out for a while now.
Thanks,
Pieter

**Comment by dhcgn** [comment]
Just waited for .NET 5, try the release https://github.com/dhcgn/BeyondCompareSQLitePlugin/releases/tag/v1.3.0

closed with #17
