### ISSUE TITLE
Database with FTS5 tables causes unhandled exception

### ISSUE THREAD

**Issue by tcobbs** [dhcgn/BeyondCompareSQLitePlugin#16]
If you run this on a SQLite database that includes [FTS5](https://www.sqlite.org/fts5.html) tables, it throws an exception:

`Error ocurred: System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database no such module: fts5`

It then exits.

**Comment by dhcgn** [comment]
I upgraded the sqlite implementation, please try the new release.

**Comment by tcobbs** [comment]
Your fix works. Thank you.
